/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.ac.tuwien.big.xaml.ui.internal.XamlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XamlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XamlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XamlActivator.getInstance().getInjector(XamlActivator.AT_AC_TUWIEN_BIG_XAML_XAML);
	}
	
}
