/*
 * generated by Xtext
 */
package eu.artist.tosca.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ToscaMarkupLanguageUiModule extends eu.artist.tosca.dsl.ui.AbstractToscaMarkupLanguageUiModule {
	public ToscaMarkupLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
