/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.group.unchanged.serializer;

import org.xtext.example.mydsl.group.unchanged.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
