/*
* generated by Xtext
*/
package at.ac.tuwien.big.xaml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.xaml.services.XamlGrammarAccess;

public class XamlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XamlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.xaml.parser.antlr.internal.InternalXamlParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.xaml.parser.antlr.internal.InternalXamlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "CAEXFile";
	}
	
	public XamlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XamlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
