/**
 * generated by Xtext
 */
package org.xtext.example.mydsl1.group.serializer;

import org.xtext.example.mydsl1.group.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
