/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.serializer;

import eu.artist.tosca.dsl.serializer.AbstractToscaMarkupLanguageSyntacticSequencer;

@SuppressWarnings("all")
public class ToscaMarkupLanguageSyntacticSequencer extends AbstractToscaMarkupLanguageSyntacticSequencer {
}
