/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.serializer;

import eu.artist.tosca.dsl.serializer.AbstractToscaDSLSyntacticSequencer;

@SuppressWarnings("all")
public class ToscaDSLSyntacticSequencer extends AbstractToscaDSLSyntacticSequencer {
}
