/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.serializer;

import eu.artist.tosca.dsl.serializer.AbstractToscaDSLSemanticSequencer;

@SuppressWarnings("all")
public class ToscaDSLSemanticSequencer extends AbstractToscaDSLSemanticSequencer {
}
