/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.serializer;

import eu.artist.tosca.dsl.serializer.AbstractToscaMarkupLanguageSemanticSequencer;

@SuppressWarnings("all")
public class ToscaMarkupLanguageSemanticSequencer extends AbstractToscaMarkupLanguageSemanticSequencer {
}
