/**
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.validation;

import at.ac.tuwien.big.amltext.validation.AbstractAMLTextValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AMLTextValidator extends AbstractAMLTextValidator {
}
