/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.validation;

import at.ac.tuwien.big.xmltext.library3.validation.AbstractLibrary3Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Library3Validator extends AbstractLibrary3Validator {
}
