/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.validation;

import eu.artist.tosca.dsl.validation.AbstractToscaDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ToscaDSLValidator extends AbstractToscaDSLValidator {
}
