/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.validation;

import eu.artist.tosca.dsl.validation.AbstractToscaMarkupLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ToscaMarkupLanguageValidator extends AbstractToscaMarkupLanguageValidator {
}
