/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.ui.contentassist;

import at.ac.tuwien.big.xaml.ui.contentassist.AbstractXamlProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class XamlProposalProvider extends AbstractXamlProposalProvider {
}
