/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.serializer;

import at.ac.tuwien.big.xmltext.library3.serializer.AbstractLibrary3SyntacticSequencer;

@SuppressWarnings("all")
public class Library3SyntacticSequencer extends AbstractLibrary3SyntacticSequencer {
}
