/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xmltext.library3.serializer;

import at.ac.tuwien.big.xmltext.library3.serializer.AbstractLibrary3SemanticSequencer;

@SuppressWarnings("all")
public class Library3SemanticSequencer extends AbstractLibrary3SemanticSequencer {
}
