/**
 * generated by Xtext
 */
package eu.artist.tosca.dsl.ui.contentassist;

import eu.artist.tosca.dsl.ui.contentassist.AbstractToscaMarkupLanguageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ToscaMarkupLanguageProposalProvider extends AbstractToscaMarkupLanguageProposalProvider {
}
