/*
* generated by Xtext
*/
package eu.artist.tosca.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import eu.artist.tosca.dsl.services.ToscaMarkupLanguageGrammarAccess;

public class ToscaMarkupLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ToscaMarkupLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected eu.artist.tosca.dsl.parser.antlr.internal.InternalToscaMarkupLanguageParser createParser(XtextTokenStream stream) {
		return new eu.artist.tosca.dsl.parser.antlr.internal.InternalToscaMarkupLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DocumentRoot";
	}
	
	public ToscaMarkupLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ToscaMarkupLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
