/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.references.unchanged.validation;

import org.xtext.example.mydsl.references.unchanged.validation.AbstractMyDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
}
