/*
* generated by Xtext
*/
package org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.group.unchanged.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRootElementTypeAccess().getGroup(), "rule__RootElementType__Group__0");
					put(grammarAccess.getElement1Access().getGroup(), "rule__Element1__Group__0");
					put(grammarAccess.getElement2Access().getGroup(), "rule__Element2__Group__0");
					put(grammarAccess.getElement2Access().getGroup_5(), "rule__Element2__Group_5__0");
					put(grammarAccess.getElement3Access().getGroup(), "rule__Element3__Group__0");
					put(grammarAccess.getElement3Access().getGroup_3(), "rule__Element3__Group_3__0");
					put(grammarAccess.getElement3Access().getGroup_3_3(), "rule__Element3__Group_3_3__0");
					put(grammarAccess.getElement3Access().getGroup_4(), "rule__Element3__Group_4__0");
					put(grammarAccess.getElement3Access().getGroup_5(), "rule__Element3__Group_5__0");
					put(grammarAccess.getRootElementTypeAccess().getElement1Assignment_3(), "rule__RootElementType__Element1Assignment_3");
					put(grammarAccess.getRootElementTypeAccess().getElement2Assignment_5(), "rule__RootElementType__Element2Assignment_5");
					put(grammarAccess.getRootElementTypeAccess().getElement3Assignment_7(), "rule__RootElementType__Element3Assignment_7");
					put(grammarAccess.getElement2Access().getModelGroupElement1Assignment_4(), "rule__Element2__ModelGroupElement1Assignment_4");
					put(grammarAccess.getElement2Access().getModelGroupElement1Assignment_5_1(), "rule__Element2__ModelGroupElement1Assignment_5_1");
					put(grammarAccess.getElement2Access().getModelGroupElement2Assignment_8(), "rule__Element2__ModelGroupElement2Assignment_8");
					put(grammarAccess.getElement2Access().getModelGroupElement3Assignment_10(), "rule__Element2__ModelGroupElement3Assignment_10");
					put(grammarAccess.getElement3Access().getRepeatableElement1Assignment_3_2(), "rule__Element3__RepeatableElement1Assignment_3_2");
					put(grammarAccess.getElement3Access().getRepeatableElement1Assignment_3_3_1(), "rule__Element3__RepeatableElement1Assignment_3_3_1");
					put(grammarAccess.getElement3Access().getRepeatableElement2Assignment_4_1(), "rule__Element3__RepeatableElement2Assignment_4_1");
					put(grammarAccess.getElement3Access().getRepeatableElement3Assignment_5_1(), "rule__Element3__RepeatableElement3Assignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.group.unchanged.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleRootElementType();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
