/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.extensions.ui.contentassist;

import org.xtext.example.mydsl.extensions.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
