/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.references.untyped.serializer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer /* implements AbstractMyDslSyntacticSequencer  */{
}
