/*
* generated by Xtext
*/
package org.xtext.example.mydsl.anyfeatureadapted.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RootElementTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RootElementType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRootElementTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cElement1Keyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElement1Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElement1Element1ParserRuleCall_3_0 = (RuleCall)cElement1Assignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPropertiesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPropertiesAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPropertiesPropertiesParserRuleCall_4_1_0 = (RuleCall)cPropertiesAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RootElementType:
		//	"RootElementType" "{" "element1" element1=Element1 ("properties" properties=Properties)? "}";
		public ParserRule getRule() { return rule; }

		//"RootElementType" "{" "element1" element1=Element1 ("properties" properties=Properties)? "}"
		public Group getGroup() { return cGroup; }

		//"RootElementType"
		public Keyword getRootElementTypeKeyword_0() { return cRootElementTypeKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"element1"
		public Keyword getElement1Keyword_2() { return cElement1Keyword_2; }

		//element1=Element1
		public Assignment getElement1Assignment_3() { return cElement1Assignment_3; }

		//Element1
		public RuleCall getElement1Element1ParserRuleCall_3_0() { return cElement1Element1ParserRuleCall_3_0; }

		//("properties" properties=Properties)?
		public Group getGroup_4() { return cGroup_4; }

		//"properties"
		public Keyword getPropertiesKeyword_4_0() { return cPropertiesKeyword_4_0; }

		//properties=Properties
		public Assignment getPropertiesAssignment_4_1() { return cPropertiesAssignment_4_1; }

		//Properties
		public RuleCall getPropertiesPropertiesParserRuleCall_4_1_0() { return cPropertiesPropertiesParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class AnyGenericConstructElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnyGenericConstruct");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAnyGenericElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAnyGenericTextParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//AnyGenericConstruct:
		//	AnyGenericElement | AnyGenericText;
		public ParserRule getRule() { return rule; }

		//AnyGenericElement | AnyGenericText
		public Alternatives getAlternatives() { return cAlternatives; }

		//AnyGenericElement
		public RuleCall getAnyGenericElementParserRuleCall_0() { return cAnyGenericElementParserRuleCall_0; }

		//AnyGenericText
		public RuleCall getAnyGenericTextParserRuleCall_1() { return cAnyGenericTextParserRuleCall_1; }
	}

	public class Element1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Element1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cElement1Action_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cElement1Keyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCitySTRINGTerminalRuleCall_3_1_0 = (RuleCall)cCityAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStreetKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStreetAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStreetSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cStreetAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Element1:
		//	{Element1} "Element1" "{" ("city" city=STRING)? ("street" street=STRING)? "}";
		public ParserRule getRule() { return rule; }

		//{Element1} "Element1" "{" ("city" city=STRING)? ("street" street=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{Element1}
		public Action getElement1Action_0() { return cElement1Action_0; }

		//"Element1"
		public Keyword getElement1Keyword_1() { return cElement1Keyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("city" city=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"city"
		public Keyword getCityKeyword_3_0() { return cCityKeyword_3_0; }

		//city=STRING
		public Assignment getCityAssignment_3_1() { return cCityAssignment_3_1; }

		//STRING
		public RuleCall getCitySTRINGTerminalRuleCall_3_1_0() { return cCitySTRINGTerminalRuleCall_3_1_0; }

		//("street" street=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"street"
		public Keyword getStreetKeyword_4_0() { return cStreetKeyword_4_0; }

		//street=STRING
		public Assignment getStreetAssignment_4_1() { return cStreetAssignment_4_1; }

		//STRING
		public RuleCall getStreetSTRINGTerminalRuleCall_4_1_0() { return cStreetSTRINGTerminalRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Properties");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPropertiesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAnyGenericElemKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAnyGenericElemAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAnyGenericElemAnyGenericConstructParserRuleCall_4_0 = (RuleCall)cAnyGenericElemAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAnyGenericElemAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAnyGenericElemAnyGenericConstructParserRuleCall_5_1_0 = (RuleCall)cAnyGenericElemAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Properties:
		//	"Properties" "{" "anyGenericElem" "{" anyGenericElem+=AnyGenericConstruct ("," anyGenericElem+=AnyGenericConstruct)*
		//	"}" "}";
		public ParserRule getRule() { return rule; }

		//"Properties" "{" "anyGenericElem" "{" anyGenericElem+=AnyGenericConstruct ("," anyGenericElem+=AnyGenericConstruct)* "}"
		//"}"
		public Group getGroup() { return cGroup; }

		//"Properties"
		public Keyword getPropertiesKeyword_0() { return cPropertiesKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"anyGenericElem"
		public Keyword getAnyGenericElemKeyword_2() { return cAnyGenericElemKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//anyGenericElem+=AnyGenericConstruct
		public Assignment getAnyGenericElemAssignment_4() { return cAnyGenericElemAssignment_4; }

		//AnyGenericConstruct
		public RuleCall getAnyGenericElemAnyGenericConstructParserRuleCall_4_0() { return cAnyGenericElemAnyGenericConstructParserRuleCall_4_0; }

		//("," anyGenericElem+=AnyGenericConstruct)*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//anyGenericElem+=AnyGenericConstruct
		public Assignment getAnyGenericElemAssignment_5_1() { return cAnyGenericElemAssignment_5_1; }

		//AnyGenericConstruct
		public RuleCall getAnyGenericElemAnyGenericConstructParserRuleCall_5_1_0() { return cAnyGenericElemAnyGenericConstructParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "String0");
		private final Keyword cStringKeyword = (Keyword)rule.eContents().get(1);
		
		/// * TODO: implement this rule and an appropriate IValueConverter * / String0 returns type::String:
		//	"String";
		public ParserRule getRule() { return rule; }

		//"String"
		public Keyword getStringKeyword() { return cStringKeyword; }
	}

	public class AnyGenericElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnyGenericElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAnyGenericElementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAnyGenericElementKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cElemNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cElemNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cElemNameSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cElemNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cElemValueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cElemValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cElemValueSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cElemValueAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAnyGenericAttrKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAnyGenericAttrAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAnyGenericAttrAnyGenericAttributeParserRuleCall_5_2_0 = (RuleCall)cAnyGenericAttrAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAnyGenericAttrAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAnyGenericAttrAnyGenericAttributeParserRuleCall_5_3_1_0 = (RuleCall)cAnyGenericAttrAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cChildElemKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cChildElemAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cChildElemAnyGenericElementParserRuleCall_6_2_0 = (RuleCall)cChildElemAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cChildElemAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cChildElemAnyGenericElementParserRuleCall_6_3_1_0 = (RuleCall)cChildElemAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//AnyGenericElement:
		//	{AnyGenericElement} "AnyGenericElement" "{" ("elemName" elemName=STRING)? ("elemValue" elemValue=STRING)?
		//	("anyGenericAttr" "{" anyGenericAttr+=AnyGenericAttribute ("," anyGenericAttr+=AnyGenericAttribute)* "}")?
		//	("childElem" "{" childElem+=AnyGenericElement ("," childElem+=AnyGenericElement)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{AnyGenericElement} "AnyGenericElement" "{" ("elemName" elemName=STRING)? ("elemValue" elemValue=STRING)?
		//("anyGenericAttr" "{" anyGenericAttr+=AnyGenericAttribute ("," anyGenericAttr+=AnyGenericAttribute)* "}")?
		//("childElem" "{" childElem+=AnyGenericElement ("," childElem+=AnyGenericElement)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{AnyGenericElement}
		public Action getAnyGenericElementAction_0() { return cAnyGenericElementAction_0; }

		//"AnyGenericElement"
		public Keyword getAnyGenericElementKeyword_1() { return cAnyGenericElementKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("elemName" elemName=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"elemName"
		public Keyword getElemNameKeyword_3_0() { return cElemNameKeyword_3_0; }

		//elemName=STRING
		public Assignment getElemNameAssignment_3_1() { return cElemNameAssignment_3_1; }

		//STRING
		public RuleCall getElemNameSTRINGTerminalRuleCall_3_1_0() { return cElemNameSTRINGTerminalRuleCall_3_1_0; }

		//("elemValue" elemValue=STRING)?
		public Group getGroup_4() { return cGroup_4; }

		//"elemValue"
		public Keyword getElemValueKeyword_4_0() { return cElemValueKeyword_4_0; }

		//elemValue=STRING
		public Assignment getElemValueAssignment_4_1() { return cElemValueAssignment_4_1; }

		//STRING
		public RuleCall getElemValueSTRINGTerminalRuleCall_4_1_0() { return cElemValueSTRINGTerminalRuleCall_4_1_0; }

		//("anyGenericAttr" "{" anyGenericAttr+=AnyGenericAttribute ("," anyGenericAttr+=AnyGenericAttribute)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"anyGenericAttr"
		public Keyword getAnyGenericAttrKeyword_5_0() { return cAnyGenericAttrKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//anyGenericAttr+=AnyGenericAttribute
		public Assignment getAnyGenericAttrAssignment_5_2() { return cAnyGenericAttrAssignment_5_2; }

		//AnyGenericAttribute
		public RuleCall getAnyGenericAttrAnyGenericAttributeParserRuleCall_5_2_0() { return cAnyGenericAttrAnyGenericAttributeParserRuleCall_5_2_0; }

		//("," anyGenericAttr+=AnyGenericAttribute)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//anyGenericAttr+=AnyGenericAttribute
		public Assignment getAnyGenericAttrAssignment_5_3_1() { return cAnyGenericAttrAssignment_5_3_1; }

		//AnyGenericAttribute
		public RuleCall getAnyGenericAttrAnyGenericAttributeParserRuleCall_5_3_1_0() { return cAnyGenericAttrAnyGenericAttributeParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("childElem" "{" childElem+=AnyGenericElement ("," childElem+=AnyGenericElement)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"childElem"
		public Keyword getChildElemKeyword_6_0() { return cChildElemKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//childElem+=AnyGenericElement
		public Assignment getChildElemAssignment_6_2() { return cChildElemAssignment_6_2; }

		//AnyGenericElement
		public RuleCall getChildElemAnyGenericElementParserRuleCall_6_2_0() { return cChildElemAnyGenericElementParserRuleCall_6_2_0; }

		//("," childElem+=AnyGenericElement)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//childElem+=AnyGenericElement
		public Assignment getChildElemAssignment_6_3_1() { return cChildElemAssignment_6_3_1; }

		//AnyGenericElement
		public RuleCall getChildElemAnyGenericElementParserRuleCall_6_3_1_0() { return cChildElemAnyGenericElementParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class AnyGenericTextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnyGenericText");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAnyGenericTextAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAnyGenericTextKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTextValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTextValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTextValueSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cTextValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AnyGenericText:
		//	{AnyGenericText} "AnyGenericText" "{" ("textValue" textValue=STRING)? "}";
		public ParserRule getRule() { return rule; }

		//{AnyGenericText} "AnyGenericText" "{" ("textValue" textValue=STRING)? "}"
		public Group getGroup() { return cGroup; }

		//{AnyGenericText}
		public Action getAnyGenericTextAction_0() { return cAnyGenericTextAction_0; }

		//"AnyGenericText"
		public Keyword getAnyGenericTextKeyword_1() { return cAnyGenericTextKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("textValue" textValue=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"textValue"
		public Keyword getTextValueKeyword_3_0() { return cTextValueKeyword_3_0; }

		//textValue=STRING
		public Assignment getTextValueAssignment_3_1() { return cTextValueAssignment_3_1; }

		//STRING
		public RuleCall getTextValueSTRINGTerminalRuleCall_3_1_0() { return cTextValueSTRINGTerminalRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class AnyGenericAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AnyGenericAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnyGenericAttributeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAttrNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAttrNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAttrNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cAttrNameAssignment_3.eContents().get(0);
		private final Keyword cAttrValueKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAttrValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAttrValueSTRINGTerminalRuleCall_5_0 = (RuleCall)cAttrValueAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//AnyGenericAttribute:
		//	"AnyGenericAttribute" "{" "attrName" attrName=STRING "attrValue" attrValue=STRING "}";
		public ParserRule getRule() { return rule; }

		//"AnyGenericAttribute" "{" "attrName" attrName=STRING "attrValue" attrValue=STRING "}"
		public Group getGroup() { return cGroup; }

		//"AnyGenericAttribute"
		public Keyword getAnyGenericAttributeKeyword_0() { return cAnyGenericAttributeKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"attrName"
		public Keyword getAttrNameKeyword_2() { return cAttrNameKeyword_2; }

		//attrName=STRING
		public Assignment getAttrNameAssignment_3() { return cAttrNameAssignment_3; }

		//STRING
		public RuleCall getAttrNameSTRINGTerminalRuleCall_3_0() { return cAttrNameSTRINGTerminalRuleCall_3_0; }

		//"attrValue"
		public Keyword getAttrValueKeyword_4() { return cAttrValueKeyword_4; }

		//attrValue=STRING
		public Assignment getAttrValueAssignment_5() { return cAttrValueAssignment_5; }

		//STRING
		public RuleCall getAttrValueSTRINGTerminalRuleCall_5_0() { return cAttrValueSTRINGTerminalRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final RootElementTypeElements pRootElementType;
	private final AnyGenericConstructElements pAnyGenericConstruct;
	private final Element1Elements pElement1;
	private final PropertiesElements pProperties;
	private final String0Elements pString0;
	private final AnyGenericElementElements pAnyGenericElement;
	private final AnyGenericTextElements pAnyGenericText;
	private final AnyGenericAttributeElements pAnyGenericAttribute;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRootElementType = new RootElementTypeElements();
		this.pAnyGenericConstruct = new AnyGenericConstructElements();
		this.pElement1 = new Element1Elements();
		this.pProperties = new PropertiesElements();
		this.pString0 = new String0Elements();
		this.pAnyGenericElement = new AnyGenericElementElements();
		this.pAnyGenericText = new AnyGenericTextElements();
		this.pAnyGenericAttribute = new AnyGenericAttributeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.anyfeatureadapted.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RootElementType:
	//	"RootElementType" "{" "element1" element1=Element1 ("properties" properties=Properties)? "}";
	public RootElementTypeElements getRootElementTypeAccess() {
		return pRootElementType;
	}
	
	public ParserRule getRootElementTypeRule() {
		return getRootElementTypeAccess().getRule();
	}

	//AnyGenericConstruct:
	//	AnyGenericElement | AnyGenericText;
	public AnyGenericConstructElements getAnyGenericConstructAccess() {
		return pAnyGenericConstruct;
	}
	
	public ParserRule getAnyGenericConstructRule() {
		return getAnyGenericConstructAccess().getRule();
	}

	//Element1:
	//	{Element1} "Element1" "{" ("city" city=STRING)? ("street" street=STRING)? "}";
	public Element1Elements getElement1Access() {
		return pElement1;
	}
	
	public ParserRule getElement1Rule() {
		return getElement1Access().getRule();
	}

	//Properties:
	//	"Properties" "{" "anyGenericElem" "{" anyGenericElem+=AnyGenericConstruct ("," anyGenericElem+=AnyGenericConstruct)*
	//	"}" "}";
	public PropertiesElements getPropertiesAccess() {
		return pProperties;
	}
	
	public ParserRule getPropertiesRule() {
		return getPropertiesAccess().getRule();
	}

	/// * TODO: implement this rule and an appropriate IValueConverter * / String0 returns type::String:
	//	"String";
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}

	//AnyGenericElement:
	//	{AnyGenericElement} "AnyGenericElement" "{" ("elemName" elemName=STRING)? ("elemValue" elemValue=STRING)?
	//	("anyGenericAttr" "{" anyGenericAttr+=AnyGenericAttribute ("," anyGenericAttr+=AnyGenericAttribute)* "}")?
	//	("childElem" "{" childElem+=AnyGenericElement ("," childElem+=AnyGenericElement)* "}")? "}";
	public AnyGenericElementElements getAnyGenericElementAccess() {
		return pAnyGenericElement;
	}
	
	public ParserRule getAnyGenericElementRule() {
		return getAnyGenericElementAccess().getRule();
	}

	//AnyGenericText:
	//	{AnyGenericText} "AnyGenericText" "{" ("textValue" textValue=STRING)? "}";
	public AnyGenericTextElements getAnyGenericTextAccess() {
		return pAnyGenericText;
	}
	
	public ParserRule getAnyGenericTextRule() {
		return getAnyGenericTextAccess().getRule();
	}

	//AnyGenericAttribute:
	//	"AnyGenericAttribute" "{" "attrName" attrName=STRING "attrValue" attrValue=STRING "}";
	public AnyGenericAttributeElements getAnyGenericAttributeAccess() {
		return pAnyGenericAttribute;
	}
	
	public ParserRule getAnyGenericAttributeRule() {
		return getAnyGenericAttributeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
