/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.datatypes.serializer;

import org.xtext.example.mydsl.datatypes.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
