/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XamlRuntimeModule extends at.ac.tuwien.big.xaml.AbstractXamlRuntimeModule {

}
