/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.serializer;

import at.ac.tuwien.big.xaml.serializer.AbstractXamlSemanticSequencer;

@SuppressWarnings("all")
public class XamlSemanticSequencer extends AbstractXamlSemanticSequencer {
}
