/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.serializer;

import at.ac.tuwien.big.xaml.serializer.AbstractXamlSyntacticSequencer;

@SuppressWarnings("all")
public class XamlSyntacticSequencer extends AbstractXamlSyntacticSequencer {
}
