/*
* generated by Xtext
*/
package at.ac.tuwien.big.xaml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XamlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.ac.tuwien.big.xaml.ui.internal.XamlActivator.getInstance().getInjector("at.ac.tuwien.big.xaml.Xaml");
	}
	
}
