/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.datatypes.validation;

import org.xtext.example.mydsl.datatypes.validation.AbstractMyDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
}
