/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MyDslProposalProvider /* implements AbstractMyDslProposalProvider  */{
}
