/**
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.validation;

import at.ac.tuwien.big.xaml.validation.AbstractXamlValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class XamlValidator extends AbstractXamlValidator {
}
