/**
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.serializer;

import at.ac.tuwien.big.amltext.serializer.AbstractAMLTextSemanticSequencer;

@SuppressWarnings("all")
public class AMLTextSemanticSequencer extends AbstractAMLTextSemanticSequencer {
}
