/**
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.serializer;

import at.ac.tuwien.big.amltext.serializer.AbstractAMLTextSyntacticSequencer;

@SuppressWarnings("all")
public class AMLTextSyntacticSequencer extends AbstractAMLTextSyntacticSequencer {
}
