/*
* generated by Xtext
*/
package eu.artist.tosca.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ToscaMarkupLanguageStandaloneSetup extends ToscaMarkupLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new ToscaMarkupLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

