/**
 * generated by Xtext
 */
package at.ac.tuwien.big.amltext.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class AMLTextQuickfixProvider extends DefaultQuickfixProvider {
}
