/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.anyfeatureadapted.serializer;

import org.xtext.example.mydsl.anyfeatureadapted.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
