/*
 * generated by Xtext
 */
package at.ac.tuwien.big.xaml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XamlUiModule extends at.ac.tuwien.big.xaml.ui.AbstractXamlUiModule {
	public XamlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
